config/routes.rb
Rails.application.routes.draw do

  resources :items
  get 'home', to: 'home#index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper

  def index
    @user = get_user

    address = "https://sandbox-id.xfers.com/api/v3/user/transfer_info"
    headers = api_header
    result = HTTParty.get address, headers: headers
    @transfers = JSON.parse result.body
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ApplicationHelper

  def new
    @user = get_user
  end

  def create
    amount = count_amount
    items = build_items
    order_id = DateTime.now.strftime("%Y%m%d%H%M%S")
    notify_link = "#{my_host}"
    return_link = "#{my_host}"
    cancel_link = "#{my_host}"
    address = "https://sandbox-id.xfers.com/api/v3/charges"
    headers = api_header
    headers["Content-Type"] = "application/json"
    body = {
      "currency" => "IDR",
      "amount" => amount,
      "notify_url" => notify_link,
      "return_url" => return_link,
      "cancel_url" => cancel_link,
      "order_id" => order_id,
      "redirect" => false,
      "description" => "unusedreddress",
      "shipping" => "2.50",
      "tax" => "0.0",
      "redirect" => false,
      "items" => items,
      "metadata" => {
        "firstname" => "Tianwei",
        "lastname" => "Liu"
      },
      "debit_only" => true
    }
    result = HTTParty.post(address, body: body.to_json, headers: headers)
    transaction = JSON.parse result.body

    redirect_to transaction["checkout_url"]
  end

  def count_amount
    amount = 0
    params["quantity"].each_with_index do |quantity, index|
      amount = amount + params["price"][index].to_f * quantity.to_f
    end
    amount
  end

  def build_items
    items = []
    params["quantity"].each_with_index do |quantity, index|
      qty = quantity.to_f
      if qty.to_f > 0
        item = {
          "quantity" => qty,
          "name" => params["name"][index],
          "price" => params["price"][index],
          "description" => params["description"][index]
        }
        items.push(item)
      end
    end
    items
  end

  def my_host
    "#{request.protocol}#{request.host_with_port}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def api_header
    {
      "X-XFERS-APP-API-KEY" => "3dehFLadwsxNUWe_sSp5ymBaQJB8yLzPyM1sRgkTDPk",
      "X-XFERS-APP-API-SECRET" => "rGZUQrjtqUzRqwsSNk9G5z8yRxmYxguZzxkrNwJze1k"
    }
  end

  def get_user
    address = "https://sandbox-id.xfers.com/api/v3/user"
    headers = api_header
    result = HTTParty.get address, headers: headers
    JSON.parse result.body
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/home/index.html.erb
<center>
  <div class="row">
    <div class="col-4">
      <%= link_to "My Shop", new_item_path %>
    </div>

    <div class="col-4">
      <strong>
        Welcome <%= "#{@user["display_name"]}" %> !
      </strong>
    </div>

    <div class="col-4">
      Balance: Rp. <%= "#{@user["available_balance"]}" %>
    </div>
  </div>

  <p>You have successfully created your wallet</p>

  <p>You can top up your wallet by transfering to the following bank</p>

  <% @transfers["transfer_info_array"].each do |transfer| %>
    <strong>Bank Name: </strong>
    <%= "#{transfer["bank_name_full"]}" %>
    <br/>
    <strong>Account number</strong>
    <%= "#{transfer["bank_account_no"]}" %>
    <br/>
    <strong>Unique id</strong>
    <%= "#{transfer["unique_id"]}" %>
  <% end %>
</center>

app/views/items/new.html.erb
<center>

  <div class="row">
    <div class="col-4">
      <%= link_to "My Shop", new_item_path %>
    </div>

    <div class="col-4">
      <strong>Shop</strong>
    </div>

    <div class="col-4">
      Balance: Rp. <%= "#{@user["available_balance"]}" %>
    </div>
  </div>

  <%= form_tag("/items", method: "post") do %>
    <%= hidden_field_tag "name", "Laptop 1", name: "name[]" %>
    <%= hidden_field_tag "name", "Laptop 2", name: "name[]" %>
    <%= hidden_field_tag "description", "Laptop 1", name: "description[]" %>
    <%= hidden_field_tag "description", "Laptop 2", name: "description[]" %>
    <%= hidden_field_tag "price", "1000000", name: "price[]" %>
    <%= hidden_field_tag "price", "2000000", name: "price[]" %>

    <div class="row">
      <div class="col-6">
        <p><strong>Laptop 1</strong></p>
        <p>1.000.000</p>
        <p><%= number_field_tag "quantity", 1, name: "quantity[]" %></p>
      </div>

      <div class="col-6">
        <p><strong>Laptop 2</strong></p>
        <p>2.000.000</p>
        <p><%= number_field_tag "quantity", 1, name: "quantity[]" %></p>
      </div>
    </div>

    <%= submit_tag "Buy" %>
  <% end %>
<center>

app/views/layouts/_nav.html.erb
<%= link_to "home", home_path %>
<%= link_to "shop", new_item_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xfers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>